// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSkill(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddSkill'](arg1, arg2, arg3, arg4, arg5);
}

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function CheckEnvironment(arg1) {
  return window['go']['main']['App']['CheckEnvironment'](arg1);
}

export function CheckToolsStatus() {
  return window['go']['main']['App']['CheckToolsStatus']();
}

export function CheckUpdate(arg1) {
  return window['go']['main']['App']['CheckUpdate'](arg1);
}

export function ClipboardGetText() {
  return window['go']['main']['App']['ClipboardGetText']();
}

export function DeleteSkill(arg1, arg2) {
  return window['go']['main']['App']['DeleteSkill'](arg1, arg2);
}

export function DownloadUpdate(arg1, arg2) {
  return window['go']['main']['App']['DownloadUpdate'](arg1, arg2);
}

export function GetCurrentProjectPath() {
  return window['go']['main']['App']['GetCurrentProjectPath']();
}

export function GetDownloadsFolder() {
  return window['go']['main']['App']['GetDownloadsFolder']();
}

export function GetEnvCheckInterval() {
  return window['go']['main']['App']['GetEnvCheckInterval']();
}

export function GetLocalCacheDir() {
  return window['go']['main']['App']['GetLocalCacheDir']();
}

export function GetSkillsDir(arg1) {
  return window['go']['main']['App']['GetSkillsDir'](arg1);
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetUserHomeDir() {
  return window['go']['main']['App']['GetUserHomeDir']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallDefaultMarketplace() {
  return window['go']['main']['App']['InstallDefaultMarketplace']();
}

export function InstallSkill(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['InstallSkill'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function InstallTool(arg1) {
  return window['go']['main']['App']['InstallTool'](arg1);
}

export function LaunchInstallerAndExit(arg1) {
  return window['go']['main']['App']['LaunchInstallerAndExit'](arg1);
}

export function LaunchTool(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['LaunchTool'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ListPythonEnvironments() {
  return window['go']['main']['App']['ListPythonEnvironments']();
}

export function ListSkills(arg1) {
  return window['go']['main']['App']['ListSkills'](arg1);
}

export function ListSkillsWithInstallStatus(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListSkillsWithInstallStatus'](arg1, arg2, arg3);
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function OpenSystemUrl(arg1) {
  return window['go']['main']['App']['OpenSystemUrl'](arg1);
}

export function PackLog(arg1) {
  return window['go']['main']['App']['PackLog'](arg1);
}

export function ReadBBS() {
  return window['go']['main']['App']['ReadBBS']();
}

export function ReadThanks() {
  return window['go']['main']['App']['ReadThanks']();
}

export function ReadTutorial() {
  return window['go']['main']['App']['ReadTutorial']();
}

export function RecoverCC() {
  return window['go']['main']['App']['RecoverCC']();
}

export function ResizeWindow(arg1, arg2) {
  return window['go']['main']['App']['ResizeWindow'](arg1, arg2);
}

export function RunEnvironmentCheckCLI() {
  return window['go']['main']['App']['RunEnvironmentCheckCLI']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectProjectDir() {
  return window['go']['main']['App']['SelectProjectDir']();
}

export function SelectSkillFile() {
  return window['go']['main']['App']['SelectSkillFile']();
}

export function SetEnvCheckInterval(arg1) {
  return window['go']['main']['App']['SetEnvCheckInterval'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function ShouldCheckEnvironment() {
  return window['go']['main']['App']['ShouldCheckEnvironment']();
}

export function ShowItemInFolder(arg1) {
  return window['go']['main']['App']['ShowItemInFolder'](arg1);
}

export function ShowMessage(arg1, arg2) {
  return window['go']['main']['App']['ShowMessage'](arg1, arg2);
}

export function UpdateLastEnvCheckTime() {
  return window['go']['main']['App']['UpdateLastEnvCheckTime']();
}

export function UpdateTool(arg1) {
  return window['go']['main']['App']['UpdateTool'](arg1);
}

export function WindowHide() {
  return window['go']['main']['App']['WindowHide']();
}
