// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckEnvironment():Promise<void>;

export function CheckToolsStatus():Promise<Array<main.ToolStatus>>;

export function CheckUpdate(arg1:string):Promise<main.UpdateResult>;

export function ClipboardGetText():Promise<string>;

export function GetCurrentProjectPath():Promise<string>;

export function GetSystemInfo():Promise<main.SystemInfo>;

export function GetUserHomeDir():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function InstallTool(arg1:string):Promise<void>;

export function LaunchTool(arg1:string,arg2:boolean,arg3:boolean,arg4:boolean,arg5:string,arg6:string,arg7:boolean):Promise<void>;

export function ListPythonEnvironments():Promise<Array<main.PythonEnvironment>>;

export function LoadConfig():Promise<main.AppConfig>;

export function OpenSystemUrl(arg1:string):Promise<void>;

export function PackLog(arg1:string):Promise<string>;

export function ReadBBS():Promise<string>;

export function ReadTutorial():Promise<string>;

export function RecoverCC():Promise<void>;

export function ResizeWindow(arg1:number,arg2:number):Promise<void>;

export function SaveConfig(arg1:main.AppConfig):Promise<void>;

export function SelectProjectDir():Promise<string>;

export function SetLanguage(arg1:string):Promise<void>;

export function ShowItemInFolder(arg1:string):Promise<void>;

export function ShowMessage(arg1:string,arg2:string):Promise<void>;
